{{- if and .Values.persistence.enabled (not .Values.persistence.keepPVC) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-{{ include "library-chart.fullname" . }}-postgresql
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize | quote }}
{{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
{{- end }}
{{- end }}
