apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-chart.fullname" . }}-postgresql
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  database: {{ .Values.postgresql.auth.database | b64enc | quote }}
