apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}-postgresql
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
  - port: 5432
