kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "library-chart.fullname" . }}-postgresql
  app.kubernetes.io/component: elasticsearch
spec:
  podSelector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: elasticsearch
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "library-chart.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: server
  policyTypes:
  - Ingress
