apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}-elasticsearch
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  ports:
  - port: 9200
