apiVersion: v1
entries:
  open-webui:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: 0.3.32
    created: "2024-10-12T00:17:21.774778+02:00"
    dependencies:
    - condition: ollama.enabled
      import-values:
      - child: service
        parent: ollama.service
      name: ollama
      repository: https://otwld.github.io/ollama-helm/
      version: '>=0.24.0'
    - condition: pipelines.enabled
      import-values:
      - child: service
        parent: pipelines.service
      name: pipelines
      repository: https://helm.openwebui.com
      version: '>=0.0.1'
    description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions
      \U0001F44B"
    digest: d432d6b43820fe099fe072fa72384870749ec6b11c6e0d8f37b09a31f0322df4
    home: https://www.openwebui.com/
    icon: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
    keywords:
    - llm
    - chat
    - web-ui
    name: open-webui
    sources:
    - https://github.com/open-webui/helm-charts
    - https://github.com/open-webui/open-webui/pkgs/container/open-webui
    - https://github.com/otwld/ollama-helm/
    - https://hub.docker.com/r/ollama/ollama
    urls:
    - https://github.com/mbtraore/helm-charts-devops/open-webui/open-webui-3.3.2.tgz
    version: 3.3.2
generated: "2024-10-12T00:17:21.772877+02:00"
