{{- if .Values.security.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "library-chart.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  ingress:
  {{- if .Values.security.networkPolicy.from }}
    - from: 
        {{- toYaml .Values.security.networkPolicy.from | nindent 8 }}
  {{- else }}
    - {}
  {{- end }}
  policyTypes:
  - Ingress
{{- end }}
