{{- if .Values.security.networkPolicy.enabled -}}
{{- if .Values.ingress.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "opensearch.fullname" . }}-2
spec:
  podSelector:
    matchLabels:
      {{- include "opensearch.selectorLabels" . | nindent 6 }}
  ingress:
  {{- with .Values.security.networkPolicy.from }}
  - from: 
  {{- toYaml . | nindent 4 }}
  {{- end }}
  policyTypes:
  - Ingress
{{- end }}
{{- end }} 