argilla:
  image:
    registry: docker.io
    repository: argilla/argilla-server
    tag: v2.3.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  storageSize: 5Gi
  auth:
    username: "argilla"
    password: "changeme"
    apikey: "argilla.apikey"
    secretkey: "changeme"
  replicaCount: 1
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3

elasticsearch:
  image:
    registry: docker.io
    repository: bitnami/elasticsearch
    tag: 8.8.2-debian-11-r23
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 5000m
      memory: 20Gi
  storageSize: 5Gi

postgresql:
  image:
    registry: docker.io
    repository: postgres
    tag: "14"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 5000m
      memory: 20Gi
  storageSize: 20Gi
  auth:
    username: "postgres"
    password: "changeme"
    database: "argilla"

# Global persistence settings
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  # storageClass: "rook-ceph-block"
  keepPVC: true
  namePostfix: "argilla-pvc"
  # postgresExistingClaim: ""
  # elasticsearchExistingClaim: ""

ingress:
  enabled: true
  hostname: "chart-example.local"
  ingressClassName: ""
  usecertManager: false
  certManagerClusterIssuer: ""
  tls: true
  annotations: []

route:
  enabled: false
    # route.openshift.io/termination: "reencrypt"
  hostname: chart-example.local
  tls:
    termination: edge
    # key:
    # certificate:
    # caCertificate:
    # destinationCACertificate:
  wildcardPolicy: None
  annotations: []

security:
  allowlist:
    enabled: false
  networkPolicy:
    enabled: false
    from: []

fullnameOverride: "argilla"

userPreferences:
  language: "en"
