{{- if .Values.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: open-webui
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
type: Opaque
stringData:
    AWS_DEFAULT_REGION: "{{ .Values.s3.defaultRegion }}"
    AWS_SECRET_ACCESS_KEY : "{{ .Values.s3.secretAccessKey }}"
    AWS_ACCESS_KEY_ID: "{{ .Values.s3.accessKeyId }}"
    AWS_SESSION_TOKEN: "{{ .Values.s3.sessionToken }}"
{{- end }}