apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}-redis
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
