security:
  password: "changeme"
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: 0.0.0.0/0

networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 9200
  dashboard: 
    port: 5601

ingress:
  enabled: false
  ingressClassName: ""
  hostname: chart-example.local
  tls: true
  useCertManager: false
  certManagerClusterIssuer: ""
  annotations: []
  
ingressDashboard:
  enabled: false
  ingressClassName: ""
  hostname: chart-example-dashboards.local
  tls: true
  useCertManager: false
  certManagerClusterIssuer: ""
  annotations: []

opensearch: 
  replicas: 3
  networkPolicy:
    create: false
    http:
      enabled: false
  securityConfig:
    enabled: true
  envFrom:
  - secretRef: 
      name: opensearch-env-secret
  persistence:
    enabled: true
    # Set to false to disable the `fsgroup-volume` initContainer that will update permissions on the persistent disk.
    enableInitChown: true
    # override image, which is busybox by default
    # image: busybox
    # override image tag, which is latest by default
    # imageTag:
    labels:
      # Add default labels for the volumeClaimTemplate of the StatefulSet
      enabled: false
    # OpenSearch Persistent Volume Storage Class
    # If defined, storageClassName: <storageClass>
    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined (the default) or set to null, no storageClassName spec is
    #   set, choosing the default provisioner.  (gp2 on AWS, standard on
    #   GKE, AWS & OpenStack)
    #
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
  resources:
    requests:
      cpu: "1000m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "10Gi"

opensearch-dashboards:
  serviceAccount:
    create: false 
  rbac:
    create: false

route:
  enabled: false
  annotations: []
    # route.openshift.io/termination: "reencrypt"
  hostname: chart-example.local
  userHostname: chart-example-user.local
  tls:
    termination: edge
    # key:
    # certificate:
    # caCertificate:
    # destinationCACertificate:
  wildcardPolicy: None

routeDashboard:
  enabled: false
  annotations: []
    # route.openshift.io/termination: "reencrypt"
  hostname: chart-example-dashboards.local
  userHostname: chart-example-user-dashboards.local
  tls:
    termination: edge
    # key:
    # certificate:
    # caCertificate:
    # destinationCACertificate:
  wildcardPolicy: None

